version: "3.7"

services:
  proxy:
    image: traefik:v2.2
    command:
      - --api.insecure=true
      - --providers.docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.docker.localhost`)"
    volumes:
      - ./nginx/public:/public
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf

  
  